source 'https://rubygems.org'
ruby '2.3.1'

gem 'rails', '4.2.3'

gem 'bootstrap-datepicker-rails'
gem 'bootstrap-filestyle-rails'
gem 'bootstrap-sass', '~> 3.3.6'
gem 'bootstrap-table-rails'
gem 'bootstrap_form'
gem 'coffee-rails', '~> 4.1.0'
gem 'exception_notification'
gem 'font-awesome-rails'
gem 'jbuilder', '~> 2.0'
gem 'jquery-rails'
gem 'jquery-ui-rails'
gem 'lazy_high_charts', git: 'https://github.com/michelson/lazy_high_charts', branch: 'master'
gem 'levenshtein-ffi'
gem 'mysql2', '~> 0.3.18'
gem 'nokogiri'
gem 'pg'
gem 'rails-i18n', git: 'https://github.com/svenfuchs/rails-i18n', branch: 'rails-4-x'
gem 'rest-client', '~> 1.6.7'
gem 'ruby-gmail'
gem 'sass-rails', '~> 5.0'
gem 'sdoc', '~> 0.4.0', group: :doc
gem 'turbolinks'
gem 'uglifier', '>= 1.3.0'
gem 'will_paginate', '~> 3.1.0'

group :development, :test do
  gem 'byebug'
  gem 'spring'
  gem 'timecop'
  gem 'web-console', '~> 2.0'
end
